engines:
  tslint:
    enabled: true
    channel: beta
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
      enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- docs/**/*
- dist/**/*
- test/**/*
- vendor/**/*
- template/**/*
- example/**/*
- build-tools/**/*
