language: node_js

dist: trusty

cache: yarn

node_js:
  - '10'
  - '8'

sudo: false

before_install:
  - yarn global add npm-run-all
  - yarn global add codeclimate-test-reporter
  - pyenv versions
  - pyenv local 2.7.14
  - pip install --user mkdocs

script:
  - yarn test

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info

deploy:
  - provider: npm
    email: 'larsvanbraam@gmail.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: '8'
    skip_cleanup: true
  - provider: script
    script: yarn deploy-docs --host=$SFTP_HOST --port=$SFTP_PORT --serverPath=$SFTP_SERVER_PATH --username=$SFTP_USERNAME --privateKey=$SFTP_KEY
    skip_cleanup: true
    on:
      tags: true
      node: '8'

addons:
  code_climate:
    repo_token:
      secure: 'ONHyuZ4TqJq07CDYNtF2RU7vM0nBIGd1fPk8MvDbWWOeXvJ5B8bnhmHejW8yxodKZLkKnnDHCWw0GPPYlVwC+NbZLGFPz3vpifcUWlPS0jyL60DiNaMxKQc7bYLFpcoQaKZ2x/QLqIxa25pGH2ivXMaK/P9r2/e17Z9IxDhLu9WPcky6FeRyD5jKYtTQqWQ/COWj0gkMjdJdoDe/9lfWVea+sJUVu57ABx53sgDtNmNvkQPfhfllF2x6ly87G0xjIqItCR6Al4DAAzHf87HRi7EnMdf3rTLga/flrkDXzcZDOoaHqN6l5pQAZQGuzq5ZdudDXDx6+uy6J6WqHG8IXCQEu7NoSQ/OI6LN5gwVgegsK/d/JZk2Kru+0lnTjDmRhCP19Qkgu2++3tEO6CPOXG7WgIULYqsXn3zvit0kSKsYekNnjRYpCyQthivz3gWGX8GS3i6TtamdL83YcOP91QoKie+S4eVmamwuttxFEIaQAz97J1bBtHgMvYgAGoT6YOr0OBKKZ2q+sak2+8KmRIP4PGWrziXMuJoJYZGf6ip7LYkRcy0vNC+piXw7wgNMU+NxytkWvNjo7UoIHlyDh3vxgpP5f940nNsGp4fF0eGdEXd8xgVKVh6QXpWS3dE+KAqKj4Kcog7Z0pIPiJk9Ed49CLwTa3df6bOqGsOqH8A='
